---
VERSION: d1.0.0.1

TIMEZONE: UTC
TIMEZONE_DIFF: +00:00

TTL: 900 #15 miniutes
THREAD_RUNNING_PERIOD: 60
KEYS:
    - 'ZS:ALERT_PLAYER_GAME_TOKEN:'
    - 'ZS:NEW_PLAYER_BIG_AVG_BET_GAME_TOKEN:'
    - 'ZS:PLAYER_DIFF_AVG_BET_GAME_TOKEN:'    
